---

- name: Install extra execution host configs
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ slurm_config_dir }}/{{ item.name }}"
    mode: "0644"
    backup: true
  loop:
    - name: acct_gather.conf
      config: slurm_acct_gather_config
      template: generic.conf.j2
    - name: cgroup.conf
      config: slurm_cgroup_config
      template: generic.conf.j2
    - name: gres.conf
      config: slurm_gres_config
      template: gres.conf.j2
  loop_control:
    label: "{{ item.name }}"
  when: item.config in vars
  notify:
    - Restart slurmctld
    - Restart slurmd
  become: true

- name: Install extra plugin configs
  ansible.builtin.template:
    src: "{{ plugin.template if plugin.template is defined else 'plugin.conf.j2' }}"
    dest: "{{ slurm_config_dir }}/{{ plugin.plugin_conf_name }}"
    mode: "0644"
    backup: true
  loop: "{{ slurm_plugins }}"
  loop_control:
    loop_var: plugin
    label: "{{ plugin.name }}"
  when: "plugin.plugin_conf_name is defined"
