---

- name: Include user creation tasks
  ansible.builtin.include_tasks: user.yml
  vars:
    _userconf: slurm_user
  when: slurm_create_user

- name: Include REST user creation tasks
  ansible.builtin.include_tasks: user.yml
  vars:
    _userconf: slurm_rest_user
  when: "slurm_create_user and slurm_is_restserver"

- name: Pull in plugin installs and configs
  ansible.builtin.include_tasks: plugins.yml
  loop: "{{ slurm_plugins }}"
  loop_control:
    loop_var: plugin
    label: plugin.name

- name: Include controller installation tasks
  ansible.builtin.include_tasks: slurmctld.yml
  when: slurm_is_controller

- name: Include execution host installation tasks
  ansible.builtin.include_tasks: slurmd.yml
  when: slurm_is_exechost

- name: Include DB installation tasks
  ansible.builtin.include_tasks: slurmdbd.yml
  when: slurm_is_dbdserver

- name: Include REST API installation tasks
  ansible.builtin.include_tasks: slurmrestd.yml
  when: slurm_is_restserver

- name: Import common tasks
  ansible.builtin.import_tasks: common.yml

- name: Ensure slurmdbd is enabled and running
  ansible.builtin.service:
    name: "{{ slurm_slurmdbd_service_name }}"
    enabled: true
    state: started
  when: "slurm_start_services and slurm_is_dbdserver"

- name: Ensure slurmctld is enabled and running
  ansible.builtin.service:
    name: "{{ slurm_slurmctld_service_name }}"
    enabled: true
    state: started
  when: "slurm_start_services and slurm_is_controller"

- name: Ensure slurmd is enabled and running
  ansible.builtin.service:
    name: "{{ slurm_slurmd_service_name }}"
    enabled: true
    state: started
  when: "slurm_start_services and slurm_is_exechost"

- name: Ensure slurmrestd is enabled and running
  ansible.builtin.service:
    name: "{{ slurm_slurmrestd_service_name }}"
    enabled: true
    state: started
  when: "slurm_start_services and slurm_is_restserver"

- name: Setup cluster on slurmdb
  include_tasks: slurmdbd_cluster.yml
  when: "slurm_start_services and slurm_is_dbdserver"
