---

- name: Fail if plugin's package specs are not given as a list
  ansible.builtin.fail:
    msg: If defined, plugin packages must be given as a list
  when:
    - plugin.pkgs is defined and plugin.pkgs is not iterable
    - plugin.pkgs is mapping
    - plugin.pkgs is string

- name: Pull in additional installable packages for {{ plugin.name }}
  ansible.builtin.set_fact:
    __slurm_packages:
      client: "{{ __slurm_packages.client + (plugin.pkgs if 'client' in plugin.targets else []) }}"
      slurmctld: "{{ __slurm_packages.slurmctld + (plugin.pkgs if 'controller' in plugin.targets else []) }}"
      slurmd: "{{ __slurm_packages.slurmd + (plugin.pkgs if 'exec' in plugin.targets else []) }}"
      slurmdbd: "{{ __slurm_packages.slurmdbd + (plugin.pkgs if 'dbd' in plugin.targets else []) }}"
      slurmrestd: "{{ __slurm_packages.slurmrestd + (plugin.pkgs if 'rest' in plugin.targets else []) }}"
  when: plugin.pkgs is defined

- name: Pull in additional main config entries for {{ plugin.name }}
  ansible.builtin.set_fact:
    __slurm_config_merged: "{{ __slurm_config_merged | combine(plugin.slurm_conf_entries | default({})) }}"
