---

# TODO: Verify this would work on Debian/Ubuntu as well
- name: Set up slurmrestd service on RedHat
  when: __slurm_redhat
  block:
    - name: Ensure the place to put systemd overrides exists
      ansible.builtin.file:
        path: /etc/systemd/system/slurmrestd.service.d
        state: directory
        mode: "0755"
      become: true

    - name: Set up systemd override
      ansible.builtin.template:
        src: slurmrestd-override.conf.j2
        dest: /etc/systemd/system/slurmrestd.service.d/override.conf
        mode: "0644"
      become: true
      register: __slurm_rest_override
      notify:
        - Restart slurmrestd

    - name: Perform a daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true
      when: __slurm_rest_override.changed
      become: true

- name: Create statesave directory
  ansible.builtin.file:
    path: /var/spool/slurm/statesave
    state: directory
    owner: "{{ slurm_user.name }}"
    group: "{{ slurm_user.group }}"
    mode: "0755"
  become: true

- name: Create unix socket locations
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ slurm_rest_user.name }}"
    group: "{{ slurm_rest_user.group }}"
    mode: "0755"
  become: true
  loop: "{{ slurm_rest_listen_sockets }}"

- name: Create cryptographic key for JWT
  ansible.builtin.command:
    cmd: "dd if=/dev/random of=/var/spool/slurm/statesave/jwt_hs256.key bs=32 count=1"
    creates: "/var/spool/slurm/statesave/jwt_hs256.key"
  become: true
  notify:
    - Restart slurmrestd

- name: Set reasonable permissions for the key
  ansible.builtin.file:
    path: "/var/spool/slurm/statesave/jwt_hs256.key"
    owner: "{{ slurm_user.name }}"
    group: "{{ slurm_user.group }}"
    mode: "0400"
  become: true
