---

- name: Create slurm group
  ansible.builtin.group:
    name: "{{ (_userconf | default({})).group }}"
    gid: "{{ (_userconf | default({})).gid | default(omit) }}"
    system: "{{ (_userconf | default({})).system | default('yes') }}"
  when: (_userconf | default({})).group is defined
  become: true

- name: Create slurm user
  ansible.builtin.user:
    name: "{{ (_userconf | default({})).name | default('slurm') }}"
    comment: "{{ (_userconf | default({})).comment | default(omit) }}"
    uid: "{{ (_userconf | default({})).uid | default(omit) }}"
    group: "{{ (_userconf | default({})).group | default(omit) }}"
    groups: "{{ (_userconf | default({})).groups | default(omit) }}"
    home: "{{ (_userconf | default({})).home | default(omit) }}"
    shell: "{{ (_userconf | default({})).shell | default(omit) }}"
    system: "{{ (_userconf | default({})).system | default('yes') }}"
  become: true
