---

- name: Restart munge
  ansible.builtin.service:
    name: munge
    state: restarted
  become: true

- name: Restart slurmdbd
  ansible.builtin.service:
    name: "{{ slurm_slurmdbd_service_name }}"
    state: "{{ 'reloaded' if slurm_no_restarts else 'restarted' }}"
  when: "slurm_start_services and slurm_is_dbdserver"
  become: true

- name: Restart slurmctld
  ansible.builtin.service:
    name: "{{ slurm_slurmctld_service_name }}"
    state: "{{ 'reloaded' if slurm_no_restarts else 'restarted' }}"
  when: "slurm_start_services and slurm_is_controller"
  become: true

- name: Restart slurmd
  ansible.builtin.service:
    name: "{{ slurm_slurmd_service_name }}"
    state: "{{ 'reloaded' if slurm_no_restarts else 'restarted' }}"
  when: "slurm_start_services and slurm_is_exechost"
  become: true

- name: Restart slurmrestd
  ansible.builtin.service:
    name: "{{ slurm_slurmrestd_service_name }}"
    state: "{{ 'reloaded' if slurm_no_restarts else 'restarted' }}"
  when: "slurm_start_services and slurm_is_restserver"
  become: true
